### ISSUE TITLE
Character encoding is wrong

### ISSUE THREAD

**Issue by MrZepto** [MSEndpointMgr/IntuneWin32App#10]
Using language specific letters like æ ø å (DK), is not working. Showing random symbols instead. Encoding in UTF-8 should fix it.

**Comment by NickolajA** [comment]
Sorry for the late reply, could you please be a bit more specific to which parts of the code you're seeing an issue with this?

**Comment by MrZepto** [comment]
It is when we use Add-IntuneWin32App.

**Comment by NickolajA** [comment]
So for instance, like the display name and similar?

**Comment by NickolajA** [comment]
I did some test in regards to this, and I could only reproduce this when I had a .ps1 file with e.g. ÅÄÖ characters for the DisplayName. Once I saved the file as 'UTF-8 with BOM' it worked as expected. How are you running it?

**Comment by aaronparker** [comment]
@NickolajA if I were to create a PR to fix this with UTF8 encoding in `Invoke-WebRequest` would that PR get approved?

**Comment by NickolajA** [comment]
Yes that'd be great and really appreciated.
