### ISSUE TITLE
Add-IntuneWin32App -Version $Version

### ISSUE THREAD

**Issue by MrZepto** [MSEndpointMgr/IntuneWin32App#11]
Posibility to add Version and Categories would be great. Doing it manually for each upload atm. ;(

**Comment by headcra6** [comment]
Really missing this functionality, has to do it manually now...

**Comment by Timhe23** [comment]
Push! Missing it too!

**Comment by NickolajA** [comment]
Added the AppVersion optional parameter in 1.3.1 that will be released shortly. For categories, it's on the todo list.
