### ISSUE TITLE
Errors due to wildcard characters in path names

### ISSUE THREAD

**Issue by jaspain** [MSEndpointMgr/IntuneWin32App#113]
Attempting to compile `pc-print-deploy-client[papercutserver.mydomain.com].msi` to an `intuenwin` file causes `New-IntuneWin32AppPackage` to fail with a "file not found" error. This unfortunate naming convention chosen by PaperCut is problematic because the square brackets in the file name are wildcard characters in PowerShell. See [about_Wildcards](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_wildcards?view=powershell-7.3).

This can be fixed by changing instances of `Test-Path -Path` to `Test-Path -LiteralPath` wherever it occurs in various `IntuneWin32App` module files.

**Comment by NickolajA** [comment]
This sounds like a reasonable and easy improvement, I'll add that to 1.4.2. Thank you for reporting!

**Comment by NickolajA** [comment]
This will be fixed in 1.4.2 where both -Path and -LiteralPath will be tested to ensure compatibility.

**Comment by jaspain** [comment]
Thank you. LiteralPath will most likely work properly. From what I could see, none of the Test-Path calls were intended to iterate over a set of files that might be returned by a wildcard in the path name. I didn't do a thorough review for other cmdlets that might accept a LiteralPath parameter vs. Path, but I did test the module myself with Test-Path -LiteralPath substituted for Test-Path -Path, and it worked with no problems. I certainly appreciate your efforts producing and maintaining this module.

**Comment by NickolajA** [comment]
I was thinking if some people were using virtual paths for some reason. Not sure if that even works, but I feel it was best to keep it for potential compatibility issues. Thanks!

**Comment by jaspain** [comment]
Yes, for backward compatibility, it makes sense to keep the -Path parameter and add another parameter set with -LiteralPath. Thanks.
