### ISSUE TITLE
Add multiple detection methods

### ISSUE THREAD

**Issue by chaendar** [MSEndpointMgr/IntuneWin32App#126]
I don't see any arguments for New-IntuneWin32AppDetectionRule(s) commands to be able to add multiple detection methods to the same app either during app creation or to add to existing apps. Is this currently possible or will I need to simply add one method and configure the others manually in the Intune GUI ?

**Comment by Klotzzz** [comment]
Hello there,

as i used it myself this way i'd like to tell, it's possible to charge and use an Array with multiple Detection Methods for example like this:

i looped something similar (in this case only files have been looked up):
{
$DetectionRuleFILE = New-IntuneWin32AppDetectionRuleFile -Existence -Path $Path -FileOrFolder $FileOrFolder -Check32BitOn64System $Check32BitOn64System -DetectionType 'exists'

$DetectionRuleCollection += $DetectionRuleFILE
}

Add-IntuneWin32App -FilePath (...) -DetectionRule $DetectionRuleCollection  (...) -Verbose
#####
Worked quite nice.


Does this help?

**Comment by chaendar** [comment]
@Klotzzz 

That gave me what I needed to figure it out, thanks!

I had originally setup my variable as an array and was adding each new rule as **$RuleArray($RuleCount) = blah blah**

As soon as I switched it to **$RuleArray += blah blah** my error went away (and revealed a different error that I dealt with in turn).

Thanks for your help!
