### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by jdarre** [MSEndpointMgr/IntuneWin32App#13]
When running Connect-MSIntuneGraph -TenantName "aaa.onmicrosoft.com", and at a later stage Connect-MSIntuneGraph -TenantName "bbb.onmicrosoft.com", the new token does refreshed correctly to connect to the new tenant. I.e. it still connect to the "aaa.onmicrosoft.com"-tenant.
Running Connect-MSIntuneGraph with -PromptBehavior Always works, but then you have to authenticate every time.

**Comment by NickolajA** [comment]
That's unfortunately one of the downsides of my old auth module (that the Connect function originates from). I'm planning on switching to MSAL.PS in the next release, since ADAL as my own module/function is based on is eventually going away.

**Comment by NickolajA** [comment]
Could you please verify if the behavior is the same in version 1.3.0 that was just released? You should be able to supply the -Interactive switch now that the module uses MSAL.PS which should enforce an interactive prompt even if there's a token in the local cache.

**Comment by jdarre** [comment]
Thanks Nicolai! I'm now able to connect to several tenants, using a multi-tenant service principal and authenticate once using the -DeviceCode switch in the first connect, and are not prompted for auth when connecting to a new tenant. Works great!

**Comment by jdarre** [comment]
Works as expected now!
