### ISSUE TITLE
Removal of dependencies from an App (v.1.4.3)

### ISSUE THREAD

**Issue by Krich17** [MSEndpointMgr/IntuneWin32App#146]
Hi,

couldn't get it working for "Remove-IntuneWin32AppDependency.ps1".

Adjusted the abstract:
`# Create relationships table using ternary conditional expression to handle empty supersedence relations
            $Win32AppRelationshipsTable = [ordered]@{
                "relationships" = if ($Supersedence) { @($Supersedence) } else { $() }
            }`

to:
`# Create relationships table using ternary conditional expression to handle empty supersedence relations
            $Win32AppRelationshipsTable = [ordered]@{
                "relationships" = @(if ($Supersedence) { @($Supersedence) } else {})
            }`

Haven't though checked Apps with existing supersedence, but without them works now.

**Comment by AlkHacNar** [comment]
will be fixed in 1.4.4

**Comment by NickolajA** [comment]
Indeed, should be fixed with 1.4.4 that's coming out any day now. Please re-open if it wasn't fixed.
