### ISSUE TITLE
Question remove supersedence/ dependency all?

### ISSUE THREAD

**Issue by AlkHacNar** [MSEndpointMgr/IntuneWin32App#147]
I don't know it it's  a bug, which is gonna be fixed in 1.4.4 already, or "intended" behavier on ms site. if I want to remove supersedence/ dependency it only removes them from the actual app, not like every app with which this app is superseded/ dependent, right?
if it's the bug issue, then it can be closed. If it's the intended way of MS, is there a way to do it?
I build a script which packages and updates my apps in Intune and I want to clean up the old superseded versions if there are to many. in the GUI I need to delete the superseded app in the next one, do I need to do the same via my script? Or does Remove-IntuneWin32AppSupersedence works both ways?

Greetings

AlkHacNar

**Comment by AlkHacNar** [comment]
or should I get all app versions, remove all supersedences via Remove-IntuneWin32AppSupersedence from each and add the new version to all not deleted? Maybe it's not the module problem but my supersedence concept?^^

**Comment by AlkHacNar** [comment]
Maybe it's my supersedence setting/ concept problem and not he modules, cuase I add the supersedence on all old versions of the app and not only on the latest? maybe I need to chain it and not add it in every app? Soory if it's a dumb question and not for the module itself

**Comment by NickolajA** [comment]
This modules intention with the removal of "relationships" is to simply do that on a per app basis, meaning the one you specify.

**Comment by AlkHacNar** [comment]
Yeah I totally understand that. My "issue" was that I have a script for app updates and it should clean up intune when there are more the x versions of an app. And as I can't delete it, if there are relations with the app, parent or child, I can't do it. Be it gui or PS. That's why I asked. But now I found a Workaround for it as I rethought my supersedence concept.
