### ISSUE TITLE
Get-IntuneWin32AppAssignment (v.1.4.3) missing usefull data from result, which was available in 1.4.1

### ISSUE THREAD

**Issue by GaborDienesLego** [MSEndpointMgr/IntuneWin32App#149]
**Hi,**

When I am using the Get-IntuneWin32AppAssignment -ID the result is missing very useful data, like ID, groupid, and target.@odata.type
Based on the new result I cannot replicate the assignment in a different application. 

**new result:**
Type                         : #microsoft.graph.groupAssignmentTarget
AppName                      : test1234
FilterID                     : 
FilterType                   : none
Intent                       : required
GroupMode                    : 
DeliveryOptimizationPriority : notConfigured
Notifications                : hideAll
RestartSettings              : 
InstallTimeSettings          : @{useLocalTime=False; 
                               startDateTime=2024-02-26T14:08:40Z; 
                               deadlineDateTime=2024-02-26T14:08:40Z}

**Old Result**
id       : 0572d602-8962-432b-aa93-61b27f743303_1_0
intent   : required
source   : direct
sourceId : 
target   : @{@odata.type=#microsoft.graph.groupAssignmentTarget; 
           deviceAndAppManagementAssignmentFilterId=; 
           deviceAndAppManagementAssignmentFilterType=none; 
           groupId=0572d602-8962-432b-aa93-61b27f743303}
settings : @{@odata.type=#microsoft.graph.win32LobAppAssignmentSettings; 
           notifications=hideAll; restartSettings=; 
           deliveryOptimizationPriority=notConfigured; autoUpdateSettings=; 
           installTimeSettings=}

Thanks for looking into this!

**Comment by NickolajA** [comment]
This should be fixed with 1.4.4 that I just committed to the repo. I'm going through the most recent issues here to see if there's something that I should attend to before release it on PowerShellGallery. So if you want to try, grab the latest function files and replace it with what you have installed locally in the modules folder, to see if it works better now.

**Comment by NickolajA** [comment]
1.4.4 is out now, please verify if the issue still persist. Reopen the issue if there's still a problem :)
