### ISSUE TITLE
Update-IntuneWin32AppPackageFile removes App Icon

### ISSUE THREAD

**Issue by chibs89** [MSEndpointMgr/IntuneWin32App#16]
As there is no Remove-IntuneWin32App cmdlet we rely on the Update-IntuneWin32AppPackageFile cmdlet.
Now as I started to use app icons in the IntunePortal I saw the issue, that when I try to override the App with the Update cmdlet the existing Icon is gone and there is no cmdlet to add the Icon afterwards or a paramet in the update cmdlet.
Could you please look into this?

**Comment by NickolajA** [comment]
Found the issue with the PATCH operation, will be fixed in 1.3.1 that will be released shortly.
