### ISSUE TITLE
Connect-MSIntuneGraph not working on fresh machine

### ISSUE THREAD

**Issue by RTMBeumer** [MSEndpointMgr/IntuneWin32App#165]
Hi there,

When i install IntuneWin32App and makes sure the install runs fine, i still get this error:
```
WARNING: An error occurred while attempting to retrieve or refresh access token. Error message: Exception calling "Create" with "1" argument(s): "Could not  
load file or assembly 'Microsoft.IdentityModel.Abstractions, Version=6.22.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The system cannot find the file specified."
```
As soon as i run Connect-MSIntuneGraph.

I cannot figure out how to solve this issued :-(

**Comment by Harrison-Tennis** [comment]
Are you able to post the full script line you are using?

E.g
Connect-MSIntuneGraph -TenantId $TenantId

**Comment by RTMBeumer** [comment]
Hi there,

Yeah sure... it´s:
Connect-MSIntuneGraph -TenantID "domain" -ClientID "ID"

"domain" being our company Microsoft domain and the same with the client id.
I do not use variables for this.

**Comment by RTMBeumer** [comment]
And it works fine on my development device which runs Server 2022.
The device i get the error is a Windows 11 machine.
If that has anything to do with it.

**Comment by l4m3us3r** [comment]
It's probably https://github.com/MSEndpointMgr/IntuneWin32App/issues/156 

This module is pretty broken right now.  Even if you do the workaround below, the module will only work for a single tenancy.  

Below is the instructions I have worked out from other people postings.

Create the app in azure:
In azure go to app registrations and register a new app.
 
in that app, Go to api permissions, add a permission, Microsoft graph, delegated permissions, 
add:
DeviceManagementManagedDevices.ReadWrite.All
DeviceManagementApps.ReadWrite.All
Group.Read.All

(note that application permissions for these 3 roles may also be needed)
 
Get the appid

Edit the powershell module
First install the powershell module, install-Module -Name "IntuneWin32App"
Edit the Connect-MSIntuneGraph.ps1
You must update lines #106 and #107 in the Connect-MSIntuneGraph.ps1 file located in the C:\Program Files\WindowsPowerShell\Modules\IntuneWin32App\1.4.4\Public folder

If installed in a user area… C:\Users\username\OneDrive\Documents\PowerShell\Modules\IntuneWin32App\1.4.4\Public

Old values: 
    $ClientID = "d1ddf0e4-d672-4dae-b554-9d5bdfd93547"
            $RedirectUri = "urn:ietf:wg:oauth:2.0:oob"


New Values:

 # Define static variables
            $ClientID = "Your client ID/App ID (not object ID) of the custom App reg with proper DeviceManagement related permissions (Application permissions)"
            $RedirectUri = "https://login.microsoftonline.com/common/oauth2/nativeclient"

Now you should be able to connect with 
Connect-MSIntuneGraph -TenantID "yourtenant.onmicrosoft.com”

**Comment by RTMBeumer** [comment]
So the guide here:
https://github.com/MSEndpointMgr/IntuneWin32App/issues/156#issuecomment-2190003235
Did help me find out, that my app registration was not setup correctly, after fixing that, it works.
But you don´t have to edit the 2 lines, if you use the -ClientID parameter:
Connect-MSIntuneGraph -TenantID "XXXXXXX.onmicrosoft.com" -ClientID "XXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX"
