### ISSUE TITLE
Remove-IntuneWin32AppDependency not working

### ISSUE THREAD

**Issue by AlkHacNar** [MSEndpointMgr/IntuneWin32App#171]
last version we had a problem with adding, now we have it in removing^^ but remove supersedence is working fine

the first error comes when you have a dependency (don't matter autoinstall or not) and the second if it's empty
have MS changed something again?

Version 1.4.4

```
PS C:\WINDOWS\system32>Remove-IntuneWin32AppDependency -id $delapp.id #-WarningAction SilentlyContinue
WARNING: An error occurred while removing dependency configuration for Win32 app: xxx. Error message: BadRequest: {
  "_version": 3,
  "Message": "A circular dependency was created while adding app relationships. - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: xxx - Url: https://fef.msub02.manage.microsoft.com/AppLifecycle_2407/StatelessAppMetadataFEService/deviceAppManagement/mobileApps('xxx')/microsoft.management.services.api.updateRelationships?api-version=502
4-05-15",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{}"
}

PS C:\WINDOWS\system32>Remove-IntuneWin32AppDependency -id $delapp.id #-WarningAction SilentlyContinue
WARNING: An error occurred while removing dependency configuration for Win32 app: xxx. Error message: BadRequest: The request is malformed or incorrect. Expected array for value of property: Collection(microsoft.graph.mobileAppRelationship)
```

**Comment by Ka1Nn** [comment]
Hello, 

It works from Powershell 5.1
Removing "AppB" Dependence of "AppA" : 

Remove-IntuneWin32AppDependency -ID $AppA.id -verbose

VERBOSE: Access token refresh is not required, remaining minutes until expiration: 42
VERBOSE: Querying for Win32 app using ID: 045bed12-0da2-4140-9b8b-21660fec47d4
VERBOSE: GET https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps/045bed12-0da2-4140-9b8b-21660fec47d4
VERBOSE: GET https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps/045bed12-0da2-4140-9b8b-21660fec47d4/relationships
VERBOSE: POST https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps/045bed12-0da2-4140-9b8b-21660fec47d4/updateRelationships

However, you mentioned encountering a circular dependency error, which suggests that a loop was created while managing the app relationships.

Could you please confirm if you are using PowerShell 7.X? This issue might be related to the version you are using.

and check the existing dependncies :
Get-IntuneWin32AppDependency -id $delapp.id

**Comment by AlkHacNar** [comment]
all good, had my sorting in the false direction, so my old app array was doing wrong
