### ISSUE TITLE
Azure Roles Required

### ISSUE THREAD

**Issue by RyanKJ21** [MSEndpointMgr/IntuneWin32App#18]
Thanks so much for working on these modules, my only question is around the required Azure roles needed to connect to graph. It works fine when a Global Admin (obviously) but I need to find the minimum required role assignments for the cmdlets to work. Thanks again

**Comment by NickolajA** [comment]
With the release of version 1.3.0, it's now using MSAL.PS and it will automatically use the 'Microsoft Intune PowerShell' app registration. This app registration has by default permissions to modify any aspect of the Intune service. Make sure you've granted tenant wide consent for this app registration in the Azure portal. You should also not require to be a Global Admin, but let's say Intune Service Administrator, unless you've implemented RBAC using Intune's built-in functionality. Then you could be more granular as to which permissions you'd allow users to have.
