### ISSUE TITLE
Issue with Authentication Header Using LocalTime and AccessToken Using UTC

### ISSUE THREAD

**Issue by armentpau** [MSEndpointMgr/IntuneWin32App#19]
When running connect-msintunegraph the variable $global:authenticationheader has the property of expireson in local time.  When functions such as Add-IntuneWin32App are called, the code to ensure required authentication header variable exists runs the following:
`$TokenLifeTime = ($Global:AuthenticationHeader.ExpiresOn - (Get-Date).ToUniversalTime()).Minutes`

This converts the current date time to UTC, with the value from the variable in local time, resulting in a negative time frame (in my case - 4 hours, -58 mins) at my current time

I can correct this while developing my pipeline currently by running the following:

`$global:authenticationheader.expireson = $global:authenticationheader.expireson.touniversaltime()`

It looks like updating the code in New-AuthenticationHeader to the below should resolve the issue:

`$AuthenticationHeader = @{
            "Content-Type" = "application/json"
            "Authorization" = $AccessToken.CreateAuthorizationHeader()
            "ExpiresOn" = $AccessToken.ExpiresOn.UtcDateTime
        }`

**Comment by NickolajA** [comment]
Appreciate the fix for this and reporting it.
