### ISSUE TITLE
New-IntuneWin32AppReturnCode missing type "Failed"

### ISSUE THREAD

**Issue by ajkenah** [MSEndpointMgr/IntuneWin32App#21]
As per the title, the New-IntuneWin32AppReturnCode module does not support the type "failed".
As a workaround, I'm currently having to manually create the hashtable with the failed type, which I'm deploying as part of the Add-IntuneWin32App deployment.

**Comment by NickolajA** [comment]
Good catch, will add this to 1.3.2. Thanks!
