### ISSUE TITLE
-whatif switch for Add-IntuneWin32AppAssignmentGroup gets ignored

### ISSUE THREAD

**Issue by neo42mgn** [MSEndpointMgr/IntuneWin32App#26]
The Command was
Add-IntuneWin32AppAssignmentGroup -ID $AppID -GroupID $GroupID -Intent required -Notification showAll -Include -WhatIf
This actually creates the assignment instead of just pretending to.
Expected Behaviour:
Whatif: Adding Assignment for AppID with GroupID

**Comment by NickolajA** [comment]
Unfortunately neither of the code in this modules have been built with support for -WhatIf, and not something I intend to re-work.
