### ISSUE TITLE
Missing Certificate authentication in Connect-MSIntuneGraph

### ISSUE THREAD

**Issue by neo42mgn** [MSEndpointMgr/IntuneWin32App#27]
I added Certificate Authentication Support to Connect-MSIntuneGraph in my fork of this project. As it does not quite work in every different case I guess it's not ready for a pull request, but maybe it helps adding this feature to the original project.
https://github.com/neo42mgn/IntuneWin32App/commit/b915838bde11f6fde95c9e13a753bec1edd8905c

**Comment by NickolajA** [comment]
Could you submit a PR with the changes you've made? I'd be happy to take a look at it.
