### ISSUE TITLE
Authentication issue after updating to Module 1.3.2

### ISSUE THREAD

**Issue by chibs89** [MSEndpointMgr/IntuneWin32App#28]
Hi, 
i used to use  Moduleversion 1.2.1 before  and upgraded to 1.3.2.
Now I get the following error Message: 
Connect-MSIntuneGraph -TenantID $tenantID
"WARNING: An error occurred while attempting to retrieve or refresh access token. Error message: The property 'Authority' cannot be found on this object. Verify that the property exists."

It is the same user which I used for connection with 1.2.1. 
Do you have any hints what the reason could be?

**Comment by chibs89** [comment]
FYI: It is still not working under 1.3.3 with the newest MSAL.PS Module installed. 
However when I manually downgrade MSAL.PS to 4.36.1.2 it is working. 
With [4.37.0.0](https://www.powershellgallery.com/packages/MSAL.PS/4.37.0.0) it is failing, when I login zu AzureAD before to grab the tenant information I need before connecting against the intunegraph.

**Comment by Joly0** [comment]
I am having a similar issue. I am trying to connect using an registrated app from my azure ad, so i assume i use the arguments TenantID, ClientID and ClientSecret, but afterwards i only get the error chibs89 already mentionend. 
It seems like it is erroring out somewhere in this try/catch https://github.com/MSEndpointMgr/IntuneWin32App/blob/644deff377ed9e1527f0c26dc99cfb137ee4fd6e/Public/Connect-MSIntuneGraph.ps1#L145

**Comment by Joly0** [comment]
Ok, i got it fixed quite easily by adding "-AzureCloudInstance 1" at the end of this line https://github.com/MSEndpointMgr/IntuneWin32App/blob/644deff377ed9e1527f0c26dc99cfb137ee4fd6e/Public/Connect-MSIntuneGraph.ps1#L147 as suggested here https://github.com/AzureAD/MSAL.PS/issues/45#issuecomment-1279193657

**Comment by NickolajA** [comment]
I can't reproduce this issue unfortunately. I just tried to authenticate using the client authentication flow (client id/client secret) using MSAL.PS 4.37.0.0 and it worked.

**Comment by jonasatgit** [comment]
I was able to reproduce the problem if I install module "Microsoft.Graph.Authentication" and use "Connect-MgGraph" for a different part of my script before using "Connect-MSIntuneGraph".

I do the following after the install module part to fix the issue for my scripts:
`Import-Module IntuneWin32App -ErrorAction SilentlyContinue
$moduleItem = Get-Module IntuneWin32App
if ($moduleItem){    
		Get-ChildItem -Path ($moduleItem.ModuleBase) -Recurse -filter 'Connect-MSIntuneGraph.ps1' | ForEach-Object {
		$stringToReplace = 'Get-MsalToken @AccessTokenArguments'
		$stringToReplaceWith = 'Get-MsalToken @AccessTokenArguments -AzureCloudInstance AzurePublic' # <- This is the fix to avoid a problem with MSAL.PS
		# Lets check if we replaced the string already        
		if (-NOT(select-string -Path $_.FullName -Pattern $stringToReplaceWith)){
			# Lets replace the string            
			$scriptContents = Get-Content $_.FullName            
			$scriptContents = $scriptContents -replace $stringToReplace, $stringToReplaceWith
			$scriptContents | Out-File -FilePath $_.FullName -Encoding utf8 -Force        
		}      
	}    
	# we neeed to re-load the module in order for the new code to work    
	Remove-Module IntuneWin32App    
	Import-Module IntuneWin32App
} `
