### ISSUE TITLE
Cannot set the Scope Tag of an app when creating it

### ISSUE THREAD

**Issue by Haacker** [MSEndpointMgr/IntuneWin32App#35]
In our environment, we use Scope Tags on many objects, including Win32Apps. This module assumes the "Default" scope and fails if the person running the code does not have rights to "Default" scope. Would it be possible to add a parameter when creating an app to be able to specify the Scope Tag(s)?

**Comment by NickolajA** [comment]
That's a great idea. I'll add that to the roadmap for 1.3.5.

**Comment by NickolajA** [comment]
This has been developed and tested. Will be added to 1.4.0 release.
