### ISSUE TITLE
[Category] setting does not exist

### ISSUE THREAD

**Issue by hidemaruki** [MSEndpointMgr/IntuneWin32App#36]
Thank you for amazing tool!

Would it be possible to add the [Category] setting for Win32 apps? 

Right now, we are trying to use IntuneWin32App in order to create big amounts of apps all at once.
Although, when setting an app to be pulled, we would like to make it easier for the users to find the app they need on the portal site by setting [Category], the setting of Win32([App information]- [Category]) does not exist on IntuneWin32App(see the image below).
We would appreciate it if you could add the feature and help us solve this problem.
・Add-IntuneWin32App.ps1
・Get-IntuneWin32App.ps1
![Intune_Category](https://user-images.githubusercontent.com/77660914/156730290-a9bc6ac0-a7b6-42c6-8c23-e9bb37d6f70c.jpg)

**Comment by CodyRWhite** [comment]
Here is a small snip that you can use to overcome this issue. It has been working without issue for me. 


```powershell 
#I place this near the top of my script to pull down all supported categories.
# Get Categories
Write-Verbose -Message "Fetching Category List from Remote Server"
$GraphURI = "https://graph.microsoft.com/beta/deviceAppManagement/mobileAppCategories"
$CategoryList = $(Invoke-RestMethod -Uri $GraphURI -Headers $Global:AuthenticationHeader -Method "GET" -ErrorAction Stop -Verbose:$false).value

<# Skipping chunks of code #>

$NewWin32App = Add-IntuneWin32App  @AppParams # This is the command that adds the app to Intune.

<# Skipping chunks of code #>

#region App Category --- Place this section somewhere in your code below the above. 
Write-Output -InputObject "Assigning category"
$Category = $CategoryList | where-object { $_.displayName -eq $BuildAppInfo.Category } #$BuildAppInfo.Category is a json file where I define the application category. 
Write-Verbose -Message "Adding app to category: $($BuildAppInfo.Category)"
$GraphURI = "https://graph.microsoft.com/Beta/deviceAppManagement/mobileApps/$($NewWin32App.id)/categories/`$ref"
$CategoryBody = @{
  "@odata.id" = "https://graph.microsoft.com/beta/deviceAppManagement/mobileAppCategories/$($Category.ID)"
} | ConvertTo-Json
$GraphResponse = Invoke-RestMethod -Uri $GraphURI -Headers $Global:AuthenticationHeader -Method "POST" -Body $CategoryBody -ContentType "application/json" -ErrorAction Stop -Verbose:$false 
#endregion App Category



```

**Comment by NickolajA** [comment]
This definitely is on the to-do list, and I'll start the work on this for version 1.4.0. Thanks for sharing the code Cody as well, that will give me a head start!

**Comment by NickolajA** [comment]
Added in 1.4.0.
