### ISSUE TITLE
New-IntuneWin32AppRequirementRuleScript.ps1 error JSON type and scriptcontent 

### ISSUE THREAD

**Issue by uwefranke** [MSEndpointMgr/IntuneWin32App#39]
error in line 245:
can you change the line 245 from  "detectionValue" = $BooleanValue" to  "detectionValue" = $BooleanValue.ToString().ToLower()

                "Boolean" {
                    # Construct ordered hash-table with least amount of required properties for default requirement rule
                    $RequirementRuleScript = [ordered]@{
                        "@odata.type" = "#microsoft.graph.win32LobAppPowerShellScriptRequirement"
                        "operator" = $BooleanComparisonOperator
                        **"detectionValue" = $BooleanValue.ToString().ToLower()**
                        "displayName" = $ScriptFileName
                        "enforceSignatureCheck" = $EnforceSignatureCheck
                        "runAs32Bit" = $RunAs32BitOn64System
                        "runAsAccount" = $ScriptContext
                        "scriptContent" = $ScriptContent
                        "detectionType" = "boolean"
                    }

https://docs.microsoft.com/de-de/graph/api/resources/intune-apps-win32lobapppowershellscriptrequirement?view=graph-rest-beta

error in line 210
            #$ScriptContent = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes([System.IO.File]::ReadAllBytes("$($ScriptFile)") -join [Environment]::NewLine))
            $ScriptContent = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes((Get-Content -Path "$($ScriptFile)" -Raw -Encoding UTF8)))

**Comment by Ka1Nn** [comment]
Hello, 

Yes, i'm totaly agree with @uwefranke for the line 210
You can easily to the test by decoding a powershell script

$ScriptFile = Get-Content -Path <Path>\Check_HwModel.ps1
#encode filecontent
$encode = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($ScriptFile))

# decode filecontent 
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($encode))

For Intune apps requirement script i used  **New-IntuneWin32AppRequirementRuleScript.ps1** to add the powershell requirement script.

If i want to get back the script: 
$result = Invoke-MSGraphRequest -Url "$graphUrl/deviceAppManagement/mobileApps/616af4f6-62af-41c7-a0d8-67f608af2721" -HttpMethod GET
[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($($result.RequirementRules.scriptContent))) 

But, return a lot of series of numbers ................

When i re-import the App requirement script manually to intune
Then i re-run the API above, the result is correct :

﻿$validModels=@("20FR","20GG","20GH")

If ( $validModels -contains (Get-WmiObject Win32_ComputerSystem).Model.Substring(0,4) ){
    Write-Output 1
    Exit 0
}

**Comment by NickolajA** [comment]
Fixed in 1.3.4 that will be released shortly.
