### ISSUE TITLE
Add-IntuneWin32AppAssignmentGroup : Parameter set cannot be resolved using the specified named parameters.

### ISSUE THREAD

**Issue by ncoschrdr** [MSEndpointMgr/IntuneWin32App#45]
Hello,

I'm currently running into the following issue trying to assign an App Assignment to a AzureAD Group:

![image](https://user-images.githubusercontent.com/55628659/176617289-dd13cd24-0d99-49c8-896b-0597cbc4c212.png)

These are the Parameters I am using: 

`Add-IntuneWin32AppAssignmentGroup -Id $IntuneWin32AppID -groupId $AzureADGroupID -Intent "available" -Verbose`

These are the things I checked:
- I checked both the App ID (using Get-IntuneWin32App) as well as the Azure AD Group ID.
- I tried it using both PowerShell 5 and the latest version of PowerShell 7
- I checked the other Cmdlets, such as Add-IntuneWin32App; they work just fine.
- I checked that I'm using the latest version 1.3.3

I would greatly appreciate any help!

Best Regards,
Nico

**Comment by Ka1Nn** [comment]
Hello, 

A parameter is missing.
You need to use this with -Include or -Exclude: 
`Add-IntuneWin32AppAssignmentGroup **-Include** -Id $IntuneWin32AppID -groupId $AzureADGroupID -Intent "available" -Verbose`

Best regards

Steven

**Comment by NickolajA** [comment]
`[parameter(Mandatory = $true, ParameterSetName = "GroupInclude", HelpMessage = "Specify the Group Mode of the assignment to be Include for the Win32 app.")]
        [switch]$Include,

        [parameter(Mandatory = $true, ParameterSetName = "GroupExclude", HelpMessage = "Specify the Group Mode of the assignment to be Exclude for the Win32 app..")]
        [switch]$Exclude,`

Include & Exclude are switch parameters, defined in separate parameter sets and will control what other parameters per set can be used. It's recommended to always specify the switch parameters in the beginning of the command, as it helps build the rest of the intended parameters.
