### ISSUE TITLE
Update the App version. Not new app, just update the App.  

### ISSUE THREAD

**Issue by rif5la** [MSEndpointMgr/IntuneWin32App#48]
Does this module allow the updating of apps. For example, I have a script that checks for new version of zoom, every time there is a new verison, the script auto packages the msi into a win32 app .intunewin,  then updates the intune application with the new .intunewin file, not replacing any other parameters. Thanks

**Comment by Skeb1ns** [comment]
I believe that is being worked on according to the v1.4.0 project.

**Comment by NickolajA** [comment]
Yes, this is something that will be introduced with version 1.4.0 using e.g. Set-IntuneWin32App.
