### ISSUE TITLE
New-IntuneWin32AppIcon - does not match the "^[A-Za-z]{1}:\\\w+\\\w+" pattern.

### ISSUE THREAD

**Issue by bickyz** [MSEndpointMgr/IntuneWin32App#5]
Hi, 
New-IntuneWin32AppIcon : Cannot validate argument on parameter 'FilePath'. The argument "D:\Gimp\gimp1.png" does not match the "^[A-Za-z]{1}:\\\w+\\\w+" pattern. Supply an 
argument that matches "^[A-Za-z]{1}:\\\w+\\\w+" and try the command again.
At line:2 char:42
+ $Icon = New-IntuneWin32AppIcon -FilePath $ImageFile

Any help would be much appreciated, thank you.

**Comment by Timhe23** [comment]
Hi, imagefilepath needs to be the full Path and Filename. Solved it like that:

$ImageFilePath = $pwd.Path + "\Source\SupportFiles\"
$ImageFileName = Get-ChildItem .\Source\SupportFiles\ -File '*.png'| Select-Object -expandproperty Name
$ImageFile = $ImageFilePath + $ImageFileName
$Icon = New-IntuneWin32AppIcon -FilePath $ImageFile

**Comment by SjoerdDerks** [comment]
Upgraded to version 1.3.3 Now I got this error

New-IntuneWin32AppIcon : Cannot validate argument on parameter 'FilePath'. The argument "C:\M365-Baseline\Apps\AutopilotBranding-master\dwe.png" does not match the "^[A-Za-z]{1}:\\\w+\\\w+
" pattern. Supply an argument that matches "^[A-Za-z]{1}:\\\w+\\\w+" and try the command again.
At line:1 char:42
+ $Icon = New-IntuneWin32AppIcon -FilePath $ImageFile
+                                          ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-IntuneWin32AppIcon], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,New-IntuneWin32AppIcon
