### ISSUE TITLE
Run without MSAL

### ISSUE THREAD

**Issue by Interrobangs** [MSEndpointMgr/IntuneWin32App#50]
I don't have MSAL and I don't need it ATM., so I made a parameter called -SkipMSAL.

Changes is in the following files:

Private/New-AuthenticationHeader.ps1
Public/Connect-MSIntuneGraph.ps1

I got this error, without MSAL:
WARNING: An error occurred while attempting to retrieve or refresh access token.

Error message: The term 'Get-MsalToken' is not recognized as the na
me of a cmdlet, function, script file, or operable program. 

Check the spelling of the name, or if a path was included, verify that the path is corre
ct and try again.

**Comment by Interrobangs** [comment]
I made a fix for my own issue, please see:

https://github.com/Interrobangs/IntuneWin32App

**Comment by NickolajA** [comment]
Not sure why you don't want/need MSAL, but thanks for sharing the code.
