### ISSUE TITLE
new parameter MinimumSupportedWindowsRelease not work in version 1.3.5

### ISSUE THREAD

**Issue by uwefranke** [MSEndpointMgr/IntuneWin32App#54]
Bad JSON request

function New-IntuneWin32AppRequirementRule

can u change line 92:
form 
            "minimumSupportedWindowsRelease" = $OperatingSystemTable[$MinimumSupportedWindowsRelease]
to
            "minimumSupportedWindowsRelease" = "$($OperatingSystemTable[$MinimumSupportedWindowsRelease])"

that work fine for me

thanks

**Comment by NickolajA** [comment]
That's odd, it's been working fine in all of my tests, there should be no need to encapsulate the string:

![image](https://user-images.githubusercontent.com/14348341/193470481-4f411f73-d1cd-427e-976b-814c2c7ab8f3.png)

**Comment by NickolajA** [comment]
There were another issue with 1.3.5 that has been addressed in 1.3.6. Hopefully that fixes your issue.

**Comment by uwefranke** [comment]
work now with version 1.3.6
