### ISSUE TITLE
Update-IntuneWin32AppPackageFile error if working dir on onedrive folder

### ISSUE THREAD

**Issue by uwefranke** [MSEndpointMgr/IntuneWin32App#55]
function Update-IntuneWin32AppPackageFile
line 152:
                        Remove-Item -Path (Split-Path -Path $IntuneWinFilePath -Parent) -Recurse -Force -Confirm:$false | Out-Null
on onedrive cant remove dir with remove-item and stop with error

this function is a workaround to delete file and dirs on onedrive:

function Remove-Dir {
    param(
        $Path
    )
    try { 
        if (Test-Path -Path $Path -PathType Container) {
            #workaround detete on Onedrive Folders
            Get-ChildItem -Path $Path -File -Recurse | remove-item  -Force
            $dirs = Get-ChildItem -Path $Path -Recurse
            $i = $dirs.Count - 1
            for ($i; $i -ge 0; $i--) { $dirs[$i].Delete($true) }
            (get-item -Path $Path).Delete($true)
            Write-Host "Delete dir ($Path)."  
        }
    }
    catch {
        Write-Error "Delete dir ($Path) failed! ($_)" 
        return $false
    }

}

**Comment by NickolajA** [comment]
I've added a fallback method similar to this that's coming in the next version, thanks for sharing!
