### ISSUE TITLE
New-IntuneWin32AppRequirementRule not setting MinimumFreeDiskSpaceInMB

### ISSUE THREAD

**Issue by emipa606** [MSEndpointMgr/IntuneWin32App#59]
When adding a requirementRule that has a MinimumFreeDiskSpaceInMB it seems that the size is never written to the app, at least not in my tests.

Example code I'm using where $applicationObject is a json-blob with application metadata with the SizeMB set to 99.6:
```ps
$sizeInMB = [math]::round($applicationObject.GeneratedValues.SizeMB * 1.5)
requirementRule = New-IntuneWin32AppRequirementRule -Architecture All -MinimumSupportedWindowsRelease 1909 -MinimumFreeDiskSpaceInMB $sizeInMB
...
Add-IntuneWin32App -FilePath $publishFile -DisplayName $appName -Description $appDescription -Publisher $appManufacturer -InstallExperience $installExperience -RestartBehavior "suppress" -DetectionRule $detectionRule -RequirementRule $requirementRule -AppVersion $newVersion -InstallCommandLine $installString -UninstallCommandLine $uninstallString -Icon $appIcon -InformationURL $changelogLink -Verbose:$VerbosePreference | Out-Null
```

The command is executed with no errors and Architecture and MinimumSupportedWindowsRelease is set accordingly but the size is still unset after publishing the application. Ive also tried to cast the $sizeInMB to int before using it with no change in result.

Would appreciate any input on this.

**Comment by g3rhard** [comment]
I can confirm, that issue still exist on the latest version.

PS: I already reported this bug in https://github.com/MSEndpointMgr/IntuneWin32App/issues/44, and it was solved...

**Comment by NickolajA** [comment]
That's obviously a bug that I didn't fix previously. I'll look into it.

**Comment by NickolajA** [comment]
See my comments in #49
