### ISSUE TITLE
Add-IntuneWin32AppAssignmentGroup Error in AvailableTime

### ISSUE THREAD

**Issue by ChrisStecher** [MSEndpointMgr/IntuneWin32App#63]
When you are trying to set an AvailableTime with Intent Available, then it fails the validation due to the deadline time is not set. 
But the DeadlineTime shouldn't be required if the Intent is Available and not required. 

Add-IntuneWin32AppAssignmentGroup -ID $AppID -Include -Intent available -GroupID $ID -AvailableTime $dateavailable 

Above line comes out with:
WARNING: Validation failed for parameter input, available date time needs to be before the current used 'as soon as possible' deadline date and time, with a offset of 1 day

It doesn't skip the check as intended in the script.

**Comment by ChrisStecher** [comment]
Just looked at it, it does work as intended in a way. 
The thing is you can from the looks of it, only use dates in the past, as availabletimes. Which doesn't make a lot of sense to have the day before yesterday as available time...

**Comment by NickolajA** [comment]
Could you share a little bit more of the code that you're trying to use here? I'd have to remind myself also how this works.

**Comment by ChrisStecher** [comment]
Found out this issue was more about me not completely understanding how Intune sees things than an error in your coding. 
Apologies.
Closing the thread
