### ISSUE TITLE
azcopy option not working when Add-IntuneWin32App executed in a job

### ISSUE THREAD

**Issue by TheQuiz03** [MSEndpointMgr/IntuneWin32App#64]
When executing Add-IntuneWin32App in script that uses multi-threaded jobs, The UseAzCopy parameter doesn't work properly. In the verbose output, the last line would be:
`VERBOSE: Using AzCopy.exe method for file transfer`

After a bit of troubleshooting i was able to resolve the issue by replacing `-NoNewWindow` with `-WindowStyle Hidden` in line 75 of the \Private\Invoke-AzureCopyUtility.ps1 file

Before:
`$TransferOperation = Start-Process -FilePath $AzCopyPath -ArgumentList "cp "$($FilePath)" "$($StorageUri)" --output-type "json"" -PassThru -NoNewWindow -ErrorAction "Stop"`

After:
`$TransferOperation = Start-Process -FilePath $AzCopyPath -ArgumentList "cp "$($FilePath)" "$($StorageUri)" --output-type "json"" -PassThru -WindowStyle Hidden -ErrorAction "Stop"`

**Comment by NickolajA** [comment]
Thank you for reporting this, that was not part of any tests that I've originally made. Will fix this in the next release to be named 1.4.0.

**Comment by NickolajA** [comment]
As testing this, changing to -WindowStyle Hidden removes the actual output. I'll add support for this in the form of a parameter switch for Add-IntuneWin32App, as I assume some people, like myself, would like to see the output from the copy operation.

**Comment by TheQuiz03** [comment]
Working as expected in 1.4.0(RC) with the AzCopyWindowStyle parameter.

**Comment by NickolajA** [comment]
Great, thanks for validating! This will be included in the final release then.
