### ISSUE TITLE
Add-IntuneWin32App with swtich "-Icon" failed

### ISSUE THREAD

**Issue by BREWERNIE** [MSEndpointMgr/IntuneWin32App#69]
Hi,

when i try to use the icon switch i get this error:

WARNUNG: An error occurred while creating the Win32 application. Error message: ModelValidationFailure: Cannot convert the literal 'D:\_my_Packages\Adobe_Acrobat-Reader-DC_2022-003-20315_DE_x86_1-0\InTune\logo.jpg' to the expected type 'Edm.Binary'.

I also tried a logo.png file instaed. The same issue.

Is my usage of the switch icon wrong ?

**Comment by BREWERNIE** [comment]
my failure.

I used the switch incorrect, sorry.

**Comment by NickolajA** [comment]
Glad you figured it out.
