### ISSUE TITLE
Get-IntuneWin32App returns max 1000 items + suggested fix for this

### ISSUE THREAD

**Issue by Lex65** [MSEndpointMgr/IntuneWin32App#74]
As the title says the max returned items is 1000
The problem was found within Invoke-IntuneGraphRequest.ps1

The "solution" which I have tested is the following. I replaced line 63 in version 1.0.5 into the following lines, and that solved my problem.
Line 63:
                  $GraphResponse = Invoke-RestMethod -Uri $GraphURI -Headers $Global:AuthenticationHeader -Method $Method -ErrorAction Stop -Verbose:$false

Into

                $GraphResponse=@()
                $GraphResponseRAW = Invoke-RestMethod -Uri $GraphURI -Headers $Global:AuthenticationHeader -Method $Method -ErrorAction Stop -Verbose:$false
                $GraphResponse+=$GraphResponseRAW
                $GraphResponseNextLink = $GraphResponseRAW."@odata.nextLink"
  
                while ($GraphResponseNextLink -ne $null){
                    $GraphResponseRAW=""
                    $GraphResponseRAW = Invoke-RestMethod -Uri $GraphResponseNextLink -Headers $Global:AuthenticationHeader -Method $Method -ErrorAction Stop -Verbose:$false
                    $GraphResponse+=$GraphResponseRAW
                    $GraphResponseNextLink = $GraphResponseRAW."@odata.nextLink"
                }

You experts can probably improve this code even more!

Credits for the base of this solution:
https://techcommunity.microsoft.com/t5/microsoft-intune/with-graph-api-we-are-only-getting-1000-devices/m-p/2682870

**Comment by CodyRWhite** [comment]
I see there is a PR for this now https://github.com/MSEndpointMgr/IntuneWin32App/pull/87

**Comment by NickolajA** [comment]
This will be addressed in 1.4.2 where the Invoke-MSGraphOperation function me and Jan Ketil Skanke have created will be used. As this module evolves, this new function will take over from Invoke-IntuneGraphRequest.
