### ISSUE TITLE
Get-IntuneWin32App fails to fetch isAssigned

### ISSUE THREAD

**Issue by emipa606** [MSEndpointMgr/IntuneWin32App#79]
It seems that the property isAssigned on the application object returned from Get-IntuneWin32App shows up as False regardless if the application has any assignments. 

Get-IntuneWin32AppAssignment returns the assignments however so using that as a workaround.

**Comment by NickolajA** [comment]
That's unfortunately how the Graph API schema representation seems to work, even if the Win32 app is in fact assigned. I just double checked on an existing assigned app, and isAssigned property was set to false.

**Comment by emipa606** [comment]
Thank you for checking on it!
