### ISSUE TITLE
Allow Supersedence and Dependency with "Add-IntuneWin32AppSupersedence"

### ISSUE THREAD

**Issue by Cyanic-Cloud** [MSEndpointMgr/IntuneWin32App#80]
Previously setting both supersedence and a dependancy on an app in Intune was not allowed, but you can now set this in the Intune GUI and through Graph, but the IntuneWin21App module has not been updated to reflect this

Image below of being able to do it through the GUI and Graph payload performing the "updateRelationship" POST request.

![image](https://user-images.githubusercontent.com/104797528/224032138-b94db385-762e-460c-a4de-fb1065b38d1b.png)

This is the same for both Add-IntuneWin32AppDependency & Add-IntuneWin32AppSupersedence

https://github.com/MSEndpointMgr/IntuneWin32App/blob/84b3d83a7e8454c3f27909017a67cf917e556747/Public/Add-IntuneWin32AppDependency.ps1#L64

https://github.com/MSEndpointMgr/IntuneWin32App/blob/c018c8d68e701de614b26156d03d4963541e7326/Public/Add-IntuneWin32AppSupersedence.ps1#L65

**Comment by rslwxyz** [comment]
Having the same problem here.. @NickolajA some help here would be greatly appreciated

**Comment by NickolajA** [comment]
You're correct, this should be updated. I've assigned it to release 1.4.1.

**Comment by Cyanic-Cloud** [comment]
Thanks @NickolajA much appreciated

**Comment by NickolajA** [comment]
This will be fixed in 1.4.2 thanks to PR #105 that now included.
